### ISSUE TITLE
We need a CRUD(Create Read Update Delete) for Brands

### ISSUE THREAD

**Issue by Coolchick1** [Coolchick1/wardrobe#7]
We are going to require a screen similar to the ViewMyProfile.
- We will need a table to list all brands. We have a DAO method to retrieve all brands
- We need a table model that will display the brand values similar to the clothing
- We will need a DAO method to add a brand
- We will need a DAO method to delete a brand
- We will need a DAO method to update a brand
- We need a dialog to add capture the details for a new brand
- We will need a button that will display the dialog to add a new brand
- We will need a button to update an existing brand
- We need a button to delete a selected brand in the table

**Comment by philiplourandos** [comment]
For the delete brand we need to do the following:
- Get the selected row from the table
- Get the Brand from the table model for the selected row
- Call the deleteBrandById on the DAO using the id in the retrieved Brand object from the table model.

From the update:
- Get the selected row from the table
- Get the Brand from the table model for the selected row
- We need to set a new instance of the BrandUpdaterPersist on the Dialog with the brand data.(Not sure if we did this)
